services:
  hello-world:
    ports: !override []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-world.rule=Host(`hello-world.pongit.be`)"
      - "traefik.http.routers.hello-world.tls.certresolver=letsencrypt"
      - "traefik.http.services.hello-world.loadbalancer.server.port=8080"
    env_file:
      - path: ../hello-world.env.dec
        required: false
    networks:
      - traefik

networks:
  traefik:
    external: true
